### ISSUE TITLE
getting error message when try to extract the .json.gz file  problem with GZIPInputStream(fileInputStream)constructor is correct with jar file once  

### ISSUE THREAD

**Issue by sdkm143** [okmich/sample-data-pipeline#2]
Jun 29, 2018 2:15:21 AM com.dezyre.hackerday.FileExtractorUtil extract
SEVERE: null
java.io.EOFException
	at java.util.zip.GZIPInputStream.readUByte(GZIPInputStream.java:264)
	at java.util.zip.GZIPInputStream.readUShort(GZIPInputStream.java:254)
	at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:163)
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:78)
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:90)
	at com.dezyre.hackerday.FileExtractorUtil.extract(FileExtractorUtil.java:42)
	at com.dezyre.hackerday.FileExtractorUtil.main(FileExtractorUtil.java:62)

Exception in thread "main" java.lang.RuntimeException
	at com.dezyre.hackerday.FileExtractorUtil.extract(FileExtractorUtil.java:50)
	at com.dezyre.hackerday.FileExtractorUtil.main(FileExtractorUtil.java:62)

**Comment by okmich** [comment]
One suggestion:

Can you extract the file using simple linux utility (tar) or using windows utilities?
The idea is that we should confirm that the archive file is not corrupted.
Once we eliminate that possibility, we can look further.

Cheers

**Comment by sdkm143** [comment]
An error occurred while loading the archive. looks like file is corrupted not able to open with utility in linux.
thanks for suggestion .

**Comment by sdkm143** [comment]
In case of appropriate json.gz file  i am able to extract the file from Linux utility and able to extract from 
case individual call of main method
A)Working fine  
 public static void main(String[] args) {
         new FileExtractorUtil("/home/cloudera/2018-06-21-10.json.gz").extract();
     }

B) not working when try this from terminal  getting same error meassge 
java -cp ./target/data-pipeline-util-1.0-SNAPSHOT.jar com.dezyre.hackerday.GithubPipelineRunner  -hdfsloc=hdfs://quickstart.cloudera:8020/user/cloudera/githubarchives -kafkaBroker=quickstart.cloudera:9092 -fileKey=2018-06-21-10

**Comment by okmich** [comment]
If I get you correctly, you mean that case A works when you hardcode the value but case B doesn't when passing the fileKey as a parameter.

Then it would be a bug.
Can you send me a zip file for your code?

**Comment by sdkm143** [comment]
Create a data pipeline based on messaging using Spark and Hive
<https://www.dezyre.com/project/hackerday-project/project-title/build-a-data-pipeline-based-on-messaging-using-spark-and-hive>
same code which you are using in data pipe line.
but for confirmation i will share with you .


Thanks
Dharmendra Kumar
