### ISSUE TITLE
issue regarding with extract the json file getting eof file exception in case of uncroupt file cases

### ISSUE THREAD

**Issue by sdkm143** [okmich/sample-data-pipeline#3]
[cloudera@quickstart file-pipeline-util]$ java -cp ./target/data-pipeline-util-1.0-SNAPSHOT.jar com.dezyre.hackerday.GithubPipelineRunner  -hdfsloc=hdfs://quickstart.cloudera:8020/user/cloudera/githubarchives -kafkaBroker=quickstart.cloudera:9092 -fileKey=2018-02-20-18
{filekey=2018-02-20-18, kafkabroker=quickstart.cloudera:9092, hdfsloc=hdfs://quickstart.cloudera:8020/user/cloudera/githubarchives}
log4j:WARN No appenders could be found for logger (org.apache.kafka.clients.producer.ProducerConfig).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Jul 03, 2018 11:55:25 PM com.dezyre.hackerday.GithubPipelineRunner run
INFO: preparing to run pipeline for key 2018-02-20-18
Jul 03, 2018 11:55:25 PM com.dezyre.hackerday.GithubPipelineRunner run
INFO: downloading filekey 2018-02-20-18
Jul 03, 2018 11:55:25 PM com.dezyre.hackerday.GithubPipelineRunner run
INFO: File for key 2018-02-20-18 downloaded to path /home/cloudera/2018-02-20-18.json.gz
Jul 03, 2018 11:55:25 PM com.dezyre.hackerday.GithubPipelineRunner run
INFO: Extracting file /home/cloudera/2018-02-20-18.json.gz
Jul 03, 2018 11:55:25 PM com.dezyre.hackerday.FileExtractorUtil extract
SEVERE: null
java.io.EOFException
	at java.util.zip.GZIPInputStream.readUByte(GZIPInputStream.java:264)
	at java.util.zip.GZIPInputStream.readUShort(GZIPInputStream.java:254)
	at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:163)
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:78)
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:90)
	at com.dezyre.hackerday.FileExtractorUtil.extract(FileExtractorUtil.java:40)
	at com.dezyre.hackerday.GithubPipelineRunner.run(GithubPipelineRunner.java:67)
	at com.dezyre.hackerday.GithubPipelineRunner.main(GithubPipelineRunner.java:109)

Jul 03, 2018 11:55:25 PM com.dezyre.hackerday.GithubPipelineRunner run
SEVERE: null
java.lang.RuntimeException
	at com.dezyre.hackerday.FileExtractorUtil.extract(FileExtractorUtil.java:48)
	at com.dezyre.hackerday.GithubPipelineRunner.run(GithubPipelineRunner.java:67)
	at com.dezyre.hackerday.GithubPipelineRunner.main(GithubPipelineRunner.java:109)

**Comment by sdkm143** [comment]
[sample-data-pipeline-master.zip](https://github.com/okmich/sample-data-pipeline/files/2169114/sample-data-pipeline-master.zip)
code which i am currently using for testing in my local .
